{
 "title": "Clickhouse DashBoard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Current  Stock ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    component AS metric,\n    SUM(closing_balance_units) AS total_stock\nFROM blood_ops.fact_inventory_day\nWHERE event_date = (\n    SELECT MAX(event_date) \n    FROM blood_ops.fact_inventory_day \n    WHERE $__timeFilter(event_date)\n)\nGROUP BY metric\nORDER BY total_stock ASC"
    }
   ]
  },
  {
   "title": "Average Number of units on a given Day ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    metric, \n    AVG(daily_total) AS total_stock\nFROM (\n    SELECT \n        event_date, \n        component AS metric, \n        SUM(closing_balance_units) AS daily_total\n    FROM blood_ops.fact_inventory_day\n    WHERE $__timeFilter(event_date)\n    GROUP BY event_date, component\n)\nGROUP BY metric\nORDER BY total_stock ASC"
    }
   ]
  },
  {
   "title": "Current Donor Eligibility Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SUM(eligible_donors) / SUM(total_donors)) * 100 AS eligibility_percentage\nFROM blood_ops.agg_donor_1w_day\nWHERE event_date = (\n    SELECT MAX(event_date) \n    FROM blood_ops.agg_donor_1w_day \n    WHERE $__timeFilter(event_date)\n)"
    }
   ]
  },
  {
   "title": "Inflow V outflow ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n    event_date AS time,\n    SUM(inflow_units) AS Inflow,\n    SUM(outflow_units) * -1 AS Outflow,\n    SUM(inflow_units) - SUM(outflow_units) AS Net_Flow\nFROM blood_ops.agg_inventory_1w_day\nWHERE $__timeFilter(event_date)\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Overall Inventory Trend by Blood Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n    event_date AS time,\n    blood_group AS metric,\n    SUM(closing_balance_units) AS inventory\nFROM blood_ops.fact_inventory_day\nWHERE $__timeFilter(event_date)\nGROUP BY time, metric\nORDER BY time"
    }
   ]
  }
 ]
}