server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://who-db:5432/who_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:who_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:who_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
