-- BLOOD BANK
CREATE TABLE blood_bank (
    bb_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    phone VARCHAR(15),
    email VARCHAR(100),
    street TEXT,
    city VARCHAR(50),
    state VARCHAR(50),
    pincode VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INVENTORY
CREATE TABLE blood_inventory_transaction (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id VARCHAR(120) NOT NULL UNIQUE,
    bb_id INT NOT NULL,
    donor_id INT,
    blood_group VARCHAR(20) NOT NULL,
    component VARCHAR(30) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    units_delta INT NOT NULL,
    running_balance_after INT NOT NULL,
    expiry_date DATE,
    event_timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bb_id) REFERENCES blood_bank(bb_id) ON DELETE CASCADE
);

CREATE INDEX idx_inventory_txn_bank_event
    ON blood_inventory_transaction (bb_id, event_timestamp);

CREATE INDEX idx_inventory_txn_day
    ON blood_inventory_transaction (event_timestamp);

CREATE INDEX idx_inventory_txn_group_component
    ON blood_inventory_transaction (blood_group, component);

-- DONOR
CREATE TABLE blood_donor (
    donor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bb_id INT,
    name VARCHAR(100),
    aadhaar_hash VARCHAR(255),
    phone VARCHAR(15),
    city VARCHAR(50),
    state VARCHAR(50),
    pincode VARCHAR(10),
    blood_group VARCHAR(20),
    age INT,
    last_donated DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bb_id) REFERENCES blood_bank(bb_id) ON DELETE SET NULL
);
