-- BLOOD BANK
CREATE TABLE blood_bank (
    bb_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    phone VARCHAR(15),
    email VARCHAR(100),
    street TEXT,
    city VARCHAR(50),
    state VARCHAR(50),
    pincode VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INVENTORY
CREATE TABLE blood_inventory (
    inventory_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bb_id INT,
    blood_group VARCHAR(5) NOT NULL,
    component_type VARCHAR(20) NOT NULL,
    units_available INT DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bb_id) REFERENCES blood_bank(bb_id) ON DELETE CASCADE
);

-- DONOR
CREATE TABLE blood_donor (
    donor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bb_id INT,
    name VARCHAR(100),
    aadhaar_hash VARCHAR(255),
    phone VARCHAR(15),
    city VARCHAR(50),
    state VARCHAR(50),
    pincode VARCHAR(10),
    blood_group VARCHAR(5),
    age INT,
    last_donated DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bb_id) REFERENCES blood_bank(bb_id) ON DELETE SET NULL
);
