apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    editable: true
    jsonData:
      index: bb_inventory_current*
      timeField: event_time
      esVersion: 8

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:9000
    editable: true
    jsonData:
      defaultDatabase: blood_ops
      username: default
      port: 9000
      protocol: native
      server: clickhouse
    secureJsonData:
      password: clickhouse
