spring.application.name=hemoconnect

# PostgreSQL (points to Docker container)
spring.datasource.url=jdbc:postgresql://localhost:5432/bloodbank
spring.datasource.username=hemo_user
spring.datasource.password=hemo_pass
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# Elasticsearch
elasticsearch.host=localhost
elasticsearch.port=9200

# Twilio
twilio.account-sid=YOUR_ACCOUNT_SID
twilio.auth-token=YOUR_AUTH_TOKEN
twilio.phone-number=YOUR_TWILIO_NUMBER

# App
server.port=8080
