server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-primary:5432/bloodbank}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hemo_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hemo_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
app.elasticsearch-url=${ELASTICSEARCH_URL:http://elasticsearch:9200}
clickhouse.url=${CLICKHOUSE_URL:http://clickhouse:8123}
clickhouse.user=${CLICKHOUSE_USER:default}
clickhouse.password=${CLICKHOUSE_PASSWORD:clickhouse}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Twilio
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp-number=${TWILIO_WHATSAPP_NUMBER}

app.fixed-otp-receiver-phone=${APP_FIXED_OTP_RECEIVER_PHONE}
app.fixed-requestor-phone=${APP_FIXED_REQUESTOR_PHONE}
app.demo-donor-phone=${APP_DEMO_DONOR_PHONE}
app.demo-donor-name=${APP_DEMO_DONOR_NAME}
app.test-whatsapp-to-phone=${APP_TEST_WHATSAPP_TO_PHONE}