server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://redcross-db:5432/redcross_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:redcross_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:redcross_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
