-- BLOOD BANK
CREATE TABLE blood_bank (
    bb_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    contact_number VARCHAR(15),
    email VARCHAR(100),
    full_address TEXT,
    postal_code VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INVENTORY
CREATE TABLE blood_inventory (
    inventory_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bb_id INT,
    blood_group VARCHAR(20) NOT NULL,
    component VARCHAR(20) NOT NULL,
    quantity INT DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bb_id) REFERENCES blood_bank(bb_id) ON DELETE CASCADE
);

-- DONOR
CREATE TABLE blood_donor (
    donor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bb_id INT,
    full_name VARCHAR(100),
    national_id VARCHAR(255),
    contact_number VARCHAR(15),
    address TEXT,
    blood_type VARCHAR(20),
    age INT,
    last_donation_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bb_id) REFERENCES blood_bank(bb_id) ON DELETE SET NULL
);
